### ISSUE TITLE
Typos and grammar issues

### ISSUE THREAD

**Issue by thanxx** [blynkkk/blynkkk.github.io#32]
1) https://www.blynk.cc/
Every project made with Blynk can be branded, and published to App Store and Google Play with your icon and app name.
Unnecessary comma after "branded":
2) http://help.blynk.cc/getting-started-library-auth-token-code-examples/getting-started 
typo: If you hardware -> if your hardware

3) There are many cases of absence of the articles before the nouns in the docs and help section. I am not an expert in English but I think the text should be checked by a competent person.

**Comment by blynkkk** [comment]
https://www.blynk.cc/ - такого сайта нет. не кликайте плиз на этот адрес
