### ISSUE TITLE
Link to http:// version of docs

### ISSUE THREAD

**Issue by SilvanCodes** [blynkkk/blynkkk.github.io#49]
https://blynk.io links to http://docs.blynk.cc as can be seen in the image below.
It should link to the https:// version of the documentation.
Only spotted on the `Documentation` card in the image, but other links should be checked as well.

![blink-insecure-link](https://user-images.githubusercontent.com/42788329/114149667-715cb580-991b-11eb-8a30-048bb399d786.PNG)

**Comment by doom369** [comment]
@blynkkk please fix.
