### ISSUE TITLE
Describe for LCD and labeled display new formatting options "pin.", "pin", "pin.##"

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynkkk.github.io#7]

**Comment by Refenz** [comment]
Labeled Valued data format.

Change the format of the output data can be the following commands:
/pin/ - displays the values without formatting
![1](https://cloud.githubusercontent.com/assets/16590099/14655492/364900f2-068b-11e6-9c52-96b282d83cbe.JPG)
/pin./ - displays the number without decimal
![2](https://cloud.githubusercontent.com/assets/16590099/14655496/396f845e-068b-11e6-896f-10bdf3520eae.JPG)
/pin.#/ - displays up to decimal
![3](https://cloud.githubusercontent.com/assets/16590099/14655499/3cb7a54c-068b-11e6-9b11-bf6bfbf4c7eb.JPG)
/pin.##/ - it displays a number with two decimal places
![4](https://cloud.githubusercontent.com/assets/16590099/14655502/3f2ca4a8-068b-11e6-92ae-c75506d645e8.JPG)
NOTE: Сhange of format is only available for virtual pins keep this in mind when designing.
